### ISSUE TITLE
Fail to Parse Parameter File

### ISSUE THREAD

**Issue by mcianfrocco** [thuem/THUNDER-demo-datasets#1]
Hi @Zarrathustra - sorry to bother you, but I wanted to point out that:

1) if you simply git clone this repo the empty.thu file is not populated correctly. So I had to download the file manually for my run

2) after including the correct empt.thu file I get an error: 

```
08/05/2019 08:56:49.801 INFO  [LOGGER_SYS] THUNDER is Initiallised With 3 Processes
08/05/2019 08:56:49.801 INFO  [LOGGER_SYS] THUNDER v1.4.11
08/05/2019 08:56:49.802 INFO  [LOGGER_SYS] Initialising Threads Setting in FFTW
08/05/2019 08:56:49.802 INFO  [LOGGER_SYS] Openning Parameter File
08/05/2019 08:56:49.802 FATAL [LOGGER_SYS] Fail to Parse Parameter File
```

Some information:
- I created a new directory within jobs named 'mike'
- Copied initial_model.mrc  and para.json into this directory
- The para.json file is identical to what you provide here in this repo
- From within my new directory (THUNDER-demo-datasets/AAV-AAVR/jobs/mike) I executed this command: 
$ mpirun -np 3 ~/software_dependencies/THUNDER/build1/thunder para.json

I'll try to reformat the .thu file on new data to see if I can get it to work, perhaps something happened during upload to github.

Mike

**Comment by Zarrathustra** [comment]
Hi,

This demo suits THUNDER v1.4.12, which has been just updated on Github. Please check https://github.com/thuem/THUNDER and install version v1.4.12. The simplest solution is execute `git pull` in CLI and get the update, and then re-compile.

Best wishes,

Mingxu

**Comment by Zarrathustra** [comment]
The parameter file (para.json) has different format, which causes this demo dataset fails on THUNDER v1.4.11.

**Comment by Zarrathustra** [comment]
Hi, @mcianfrocco, I wonder that whether you have successfully run this demo dataset using THUNDER 1.4.12.

Best regards.

Mingxu

**Comment by mcianfrocco** [comment]
Hi @Zarrathustra - Thanks for checking in on this. There is still an issue with cloning the data from Github. It's confusing as I see the .mrcs files are ~16 MB, but when I clone the repo using git clone or download the .zip file for the whole repo, all of the .mrcs are not complete and are only 133 bytes. 

I'd encourage you to try cloning the repo to see if it works for you.

In the meantime, I've gotten THUNDER 1.4.12 to work on other data I have in lab - thanks!

Thanks,
Mike

**Comment by Zarrathustra** [comment]
Hi @mcianfrocco, it may be caused by no existence of git-lfs (Git Large File Storage) in your environment.

Check https://git-lfs.github.com, please. As Github has file size limit, it is only possible to upload large files using git-lfs. It may be also required to download large files using git-lfs.

Best regards,

Mingxu

**Comment by mcianfrocco** [comment]
Oh I see - thanks for pointing this out. I will try this.

You should also consider adding this information into the README as I consider myself a moderately experience git user but had never heard of git-lfs.

Mike
